name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as Stale as no actions have been made within X amount of days'
        stale-pr-message: 'This p/r has been marked as Stale as no actions have been made within X amount of days'
        stale-issue-label: 'Meta: Invalid'
        stale-pr-label: 'Meta: Invalid'
